spring:
  application:
    name: feature-toggle-read
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5434/feature_toggle_read
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feature-toggle-read

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([${spring.application.name:-app}]){green} %clr([%X{correlationId:--}]){yellow} %clr([%X{actor:--}]){cyan} %clr(%-5level) -> %msg%n"

topics:
  feature-toggle-events: feature-toggle-events
  feature-toggle-configuration-events: feature-toggle-configuration-events

server:
  port: 8083